repos: 
  # black
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=88
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""

        language_version: python3
 # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,F403,E402,W291,F401"

  # #MyPy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.0
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports"]
  #       additional_dependencies: ['types-requests']

  # #Bandit
  # - repo: https://github.com/PyCQA/bandit
  #   rev: '1.7.4'
  #   hooks:
  #   - id: bandit

  # #pydocstyle
  # -   repo: https://github.com/pycqa/pydocstyle
  #     rev: 6.3.0 
  #     hooks:
  #     -   id: pydocstyle