version: "3"

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: unless-stopped
    ports:
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${LOGIN_RABBITMQ}
      - RABBITMQ_DEFAULT_PASS=${PASS_RABBITMQ}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  app:
    env_file:
      - .env
    container_name: test-app
    build: ./
    command: bash -c "alembic upgrade head && python runserver.py"
    volumes:
      - .:/app
    ports:
      - 8087:8000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
