"""change wallet id to uuid & make m2m conn with transactions

Revision ID: 223f515a235e
Revises: f77f1a45393e
Create Date: 2023-03-07 20:59:40.292678

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "223f515a235e"
down_revision = "f77f1a45393e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "association_table",
        sa.Column("wl_id", sa.Integer(), nullable=True),
        sa.Column("tr_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tr_id"],
            ["transaction_data.transaction_id"],
        ),
        sa.ForeignKeyConstraint(
            ["wl_id"],
            ["wallet_data.wallet_id"],
        ),
    )
    op.add_column(
        "transaction_data", sa.Column("from_wallet_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "transaction_data", sa.Column("to_wallet_id", sa.UUID(), nullable=True)
    )
    op.drop_constraint(
        "transaction_data_user_id_fkey", "transaction_data", type_="foreignkey"
    )
    op.drop_constraint(
        "transaction_data_wallet_id_fkey", "transaction_data", type_="foreignkey"
    )
    op.drop_column("transaction_data", "wallet_id")
    op.drop_column("transaction_data", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_data",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transaction_data",
        sa.Column("wallet_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transaction_data_wallet_id_fkey",
        "transaction_data",
        "wallet_data",
        ["wallet_id"],
        ["wallet_id"],
    )
    op.create_foreign_key(
        "transaction_data_user_id_fkey",
        "transaction_data",
        "user_data",
        ["user_id"],
        ["user_id"],
    )
    op.drop_column("transaction_data", "to_wallet_id")
    op.drop_column("transaction_data", "from_wallet_id")
    op.drop_table("association_table")
    # ### end Alembic commands ###
